### ISSUE TITLE
500 Errors when simple objects are posted

### ISSUE THREAD

**Issue by stopthatastronaut** [DimensionDataCBUSydney/PowerShell.REST.API#1]
I have a Simple WebMethod configured as follows:
```

<WebMethod Name="internals" AsJob="false" PowerShellPath="internals.ps1">
    <Parameters>
        <Parameter Name="thingy" Type="object" />
    </Parameters>
</WebMethod>
```

I call this using PowerShell as follows

`Invoke-Restmethod http://127.0.0.1/api/grapnel/internals -method POST -body '[{"thingy":"thingy"}]'`

And I get the expected 200 and some output

However if I call this using

`Invoke-Restmethod http://127.0.0.1/api/grapnel/internals -method POST -body '{"thingy":"thingy"}'`

I get a 500 error and the message "Cannot find all parameters required."

I've tracked this to ProcessRequestAsync, in the following block

```
var queryStrings = new Dictionary<string, string>();
JToken token = documentContents.StartsWith("[") ? (JToken)JArray.Parse(documentContents) : JObject.Parse(documentContents);
											
foreach (var details in token)
{
						 
    var name = details.First.First.ToString();  
    var value = details.Last.First.ToString();

   queryStrings.Add(name, value);
}
```

By examining the objects returned from JObject.Parse(), it looks like `.First` is null, whereas the same objects work when returned from JArray.Parse() 

I'm about to fork and try to debug this, thought it was worth putting in an issue anyway

**Comment by stopthatastronaut** [comment]
Update: I've got what I _think_ is a fix on my fork of the project.

**Comment by tintoy** [comment]
Hi - thanks for taking a look at this! I'd like to know more about the issue, so if you could post a link to the branch you're working on I'm happy to take a look.

**Comment by tintoy** [comment]
Yes, it looks like you're right - the existing code can't handle array items that are empty object-literals. For example:

```json
[
    { "this_will_not_cause_a_crash": "but_the_following_item_will" },
    { }
]
```

You've already done most of the work in finding and fixing this; I'm just going to put this example solution here for future reference:

```csharp
JToken requestBody = JToken.Parse(documentContents);

JArray requestArray = requestBody as JArray;
if (requestArray != null)
{
    foreach (JObject requestItem in requestArray.OfType<JObject>()) // using System.Linq
    {
        foreach (JProperty property in requestItem.Properties())
        {
            string propertyValue = null;
            if (property.Value.Type != JTokenType.Null)
                propertyValue = property.Value.ToString();

            queryStrings.Add(property.Name, propertyValue);
        }
    }
}

JObject requestObject = requestBody as JObject;
if (requestObject != null)
{
    foreach (JProperty property in requestObject.Properties())
    {
        string propertyValue = null;
        if (property.Value.Type != JTokenType.Null)
            propertyValue = property.Value.ToString();

        queryStrings.Add(property.Name, propertyValue);
    }
}
```

If you can just have a quick look at the comments I left in your PR and make some minor adjustments then we can merge your fix :-)

PS. If you don't have the time, let me know and I'm happy can accept your PR as-is and do any minor tidying-up later.

**Comment by tintoy** [comment]
Closing #1.
