### ISSUE TITLE
API Doesn't return message

### ISSUE THREAD

**Issue by stuartin** [DimensionDataCBUSydney/PowerShell.REST.API#4]
Hi,
Firstly, this sounds like an excellent project that would be very very useful so thankyou!

I'm having a problem with the basic functionality though, I've got the Host up and running and its accepting calls to the correct endpoint (all on my local machine).
The problem is that the JSON that the API is returning isn't what is in the .json file that is create in C:\Temp\. Instead I'm just getting what looks like some kind of identifier "97d5fa15-a27c-4355-800d-c34555859d6b"

To re-produce:
-Download the v0.9.0-develop build that is available.
-Run the host: DynamicPowerShellApi.Host.exe --console
-Browse to: http://localhost:9000/api/Example/GetMessage?message=hello
-JSON is: "97d5fa15-a27c-4355-800d-c34555859d6b"

Expected Results:
-JSON should return the .json file in C:\Temp such as below:
{
  "message": "hello"
}

Thanks again

**Comment by mesdocs** [comment]
Hi,
I had the same behaviour since the example is configured to be executed as a job.
Please look at the configuration file and search for the GetMessage web method.
Change the AsJob property to false, then restart the host application. You should get the result you expect.

**Comment by tonybaloney** [comment]
The `AsJob` argument is for long-running tasks. It will give you a task ID back, you can then fetch the status of the job and later on, the results.
If you want to run them synchronously, set that value to False
