### ISSUE TITLE
How to allow CORS?

### ISSUE THREAD

**Issue by jonbrohauge** [DimensionDataCBUSydney/PowerShell.REST.API#5]
Using this as a REST API as a backend for some AngularJS, I get an error:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '[MY SERVER]' is therefore not allowed access.

This means that there is a need to set some http headers on the response.
How is this doable?

**Comment by tonybaloney** [comment]
This is not currently supported, but you would need to (in a fork) edit the `Startup.cs` file and add a configuration option for CORS headers in the response.

https://github.com/DimensionDataCBUSydney/PowerShell.REST.API/blob/master/Owin/Startup.cs#L48

There is a WebAPI CORS package, which can be enabled like this:
https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api#enable-cors
